apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr
  namespace: media
spec:
  sourcePVC: config-overseerr-0
  trigger:
    schedule: "0 5 * * *"
  restic:
    repository: overseerr-volsync-restic
    copyMethod: Clone
    storageClassName: linstor-r1
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
    moverSecurityContext:
      fsGroup: 65537
