apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex
  namespace: media
spec:
  sourcePVC: config-plex-0
  trigger:
    schedule: "30 8 * * *"
  restic:
    repository: plex-volsync-restic
    copyMethod: Clone
    storageClassName: linstor-r1
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
    moverSecurityContext:
      runAsUser: 1029
      runAsGroup: 65537
      fsGroup: 65537
