apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr
  namespace: media
spec:
  sourcePVC: config-sonarr-0
  trigger:
    schedule: "0 3 * * *"
  restic:
    repository: sonarr-volsync-restic
    copyMethod: Clone
    storageClassName: linstor-r3
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
    moverSecurityContext:
      runAsUser: 1029
      runAsGroup: 65537
      fsGroup: 65537
