apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tautulli
  namespace: media
spec:
  sourcePVC: config-tautulli-0
  trigger:
    schedule: "30 3 * * *"
  restic:
    repository: tautulli-volsync-restic
    copyMethod: Clone
    storageClassName: linstor-r1
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
