{
 "title": "VPA Recommendations",
 "description": "A dashboard to visualize metrics about the Vertical Pod Autoscaler using the generated Prometheus metrics of the Kube-State-Metrics",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_verticalpodautoscaler_labels, cluster)"
    }
   },
   {
    "name": "recommendation",
    "label": "Recommendation",
    "query": "target,uncappedtarget,lowerbound,upperbound"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_verticalpodautoscaler_labels{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": {
     "query": "label_values(kube_verticalpodautoscaler_labels{cluster=\"$cluster\", namespace=\"$namespace\"}, target_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory $recommendation vs Memory Usage",
   "type": "graph",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container!=\"\", container!=\"POD\"}) by (container,pod)",
     "legendFormat": "{{pod}}-{{container}} actual usage"
    },
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\"}) by (container)",
     "legendFormat": "{{container}} recommendation"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}} recommendation"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod)",
     "legendFormat": "{{pod}}-{{container}} requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod)",
     "legendFormat": "{{pod}}-{{container}} limits"
    }
   ]
  },
  {
   "title": "CPU $recommendation vs CPU Usage",
   "type": "graph",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$targetName-(.+)\", container!=\"\", container!=\"POD\"}[$__rate_interval])) by (container,pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} actual usage"
    },
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\"}) by (container) * 1000",
     "legendFormat": "{{container}} recommendation"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{cluster=\"$cluster\", namespace=\"$namespace\", target_name=\"$targetName\", resource=\"cpu\"}) by (container) * 1000",
     "legendFormat": "{{container}} recommendation"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} limits"
    }
   ]
  }
 ]
}