---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
  ref:
    tag: "8.2.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 30m
  releaseName: kube-state-metrics
  targetNamespace: o11y
  chartRef:
    kind: OCIRepository
    name: kube-state-metrics
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi

    prometheus:
      monitor:
        enabled: false

    selfMonitor:
      enabled: false
