apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo-grafana.yaml
  - o11y.yaml
  - loki.yaml
  - mimir.yaml
  - kube-state-metrics.yaml
  - kopiur.yaml
  - alloy.yaml
  - grafana.yaml
  - scrutiny-influxdb.yaml
  - helmrepo-influxdata.yaml
  - homebridge.yaml
  - linstor-gui.yaml
  - media.yaml
  - media-overseerr.yaml
  - media-plex.yaml
  - media-prowlarr.yaml
  - media-radarr.yaml
  - media-sonarr.yaml
  - media-tautulli.yaml
  - spoolman.yaml
  - spoolman-bambu.yaml
  - volsync.yaml
