apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: tls-handshake-daemon
  namespace: piraeus-datastore
spec:
  internalTLS:
    tlsHandshakeDaemon: true
    certManager:
      kind: Issuer
      name: linstor-cluster-internal-ca
