apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr
  namespace: media
spec:
  sourcePVC: config-overseerr-0
  trigger:
    schedule: "0 3 * * *"
  restic:
    repository: overseerr-restic
    copyMethod: Snapshot
    volumeSnapshotClassName: linstor-r3
    cacheCapacity: 1Gi
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 5
      monthly: 6
