apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bindery-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-r3
  resources:
    requests:
      storage: 4Gi
