apiVersion: v1
kind: Service
metadata:
  name: bindery
  namespace: media
  labels:
    app: bindery
spec:
  selector:
    app: bindery
  ports:
    - name: http
      port: 8787
      targetPort: http
      protocol: TCP
