apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bindery-tls
  namespace: media
spec:
  secretName: bindery-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - bindery.i.recompiled.org
