apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-httproute.yaml
  - metrics-tls-cert.yaml
  - grafana-httproute.yaml
  - grafana-tls-cert.yaml
  - loki-httproute.yaml
  - loki-tls-cert.yaml
