apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
  namespace: system-upgrade
spec:
  talos:
    # renovate: datasource=github-tags depName=siderolabs/talos
    version: v1.13.5
  policy:
    placement: soft
    nodrain: true
  parallelism: 1
  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")
      timeout: 10m
