---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/piraeusdatastore/piraeus-operator/piraeus
  ref:
    tag: "2.10.8"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: linstor-cluster
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/piraeusdatastore/helm-charts/linstor-cluster
  ref:
    tag: "1.1.1"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 30m
  releaseName: piraeus-operator
  targetNamespace: piraeus-datastore
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: piraeus-operator
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor-cluster
  namespace: flux-system
spec:
  interval: 30m
  releaseName: linstor-cluster
  targetNamespace: piraeus-datastore
  dependsOn:
    - name: piraeus-operator
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: linstor-cluster
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    storageClass:
      enabled: false
    createInternalTLS: "cert-manager"
    linstorCluster:
      properties:
        - name: DrbdOptions/Net/tls
          value: "yes"
