apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-htpasswd
    namespace: auth
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:N2PqZAMPeVl8U7XVgJ4qHojgW/HvkEj2sg9GOU/Y08q1hntPzVfn57fsV75Raqz+Sf6iM8XBMoXqHs+u35WvEEby9Wdc0lTyK+ys,iv:xbM12RGdpD/R01YrgLhaMrSdqbxZNt0iN4KEhl5cPK0=,tag:2yA/PmQm/RT4KtOgkFEA6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU3hUS1d1L2l4TFVubUVR
            YnZwZFFmVW10ZnFZdE9zNUR4Z0FKZ2NqRGk4ClBudnNDSkJXcXk1ZHlGUk5BWGdk
            aVozTlovZnhFSzlacG0yUmFSYjhjQXcKLS0tIFhkb0pGNVpYaGlXSE1GNWJKZkVw
            QTlsQXplQWcwK21DWVNCSmhRTFcydEEKxYT2KDF/JjzV4iv3tdSAx9pa0dQrmKbc
            2j3MGLHD38Jl6WI+PHAHgXsHx3B7dKs4/yfUHQWWB9sJsDzri0MgUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T00:04:32Z"
    mac: ENC[AES256_GCM,data:SSliLTM5BarciKQihqSTsVYkEdK4aOG4pdbUSIEsFyFst6UpcOfctGEnEgctSkXdRabbHxcbCflUwecXnrtjx9hpmndzU4rdfjj6aB99U2QKafQXQZ8db2gZ71OzeC+WhLDxgA/F/4W0jjtwXvehzWWDkTKnGlJip23RdAyKgnM=,iv:w4B5Kn+zoimyLaUses8gjkpMc/4NWdVkzX+b0/aNJuw=,tag:1sGW6DobXb7HJwKpmoeyOw==,type:str]
    version: 3.13.3
