---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-auth
  namespace: auth
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        location = /healthz {
            auth_basic off;
            access_log off;
            return 200 "ok\n";
        }

        location / {
            auth_basic           "Restricted";
            auth_basic_user_file /etc/nginx/htpasswd/users;
            try_files /dev/null @ok;
        }

        location @ok {
            internal;
            return 200;
        }
    }
