apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - oauth2-proxy-secret.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - oauth2-proxy-middleware.yaml
  - oauth2-proxy-pdb.yaml
  - oauth2-proxy-certificate.yaml
  - oauth2-proxy-ingressroute.yaml
  - basic-auth-htpasswd-secret.yaml
  - basic-auth-configmap.yaml
  - basic-auth-deployment.yaml
  - basic-auth-service.yaml
  - basic-auth-middleware.yaml
  - basic-auth-pdb.yaml
