apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - basic-auth-secret.yaml
  - basic-auth-middleware.yaml
  - oauth2-proxy-secret.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - oauth2-proxy-middleware.yaml
  - oauth2-proxy-pdb.yaml
  - oauth2-proxy-certificate.yaml
  - oauth2-proxy-ingressroute.yaml
  - oauth2-proxy-htpasswd-secret.yaml
  - oauth2-proxy-basic-deployment.yaml
  - oauth2-proxy-basic-service.yaml
  - oauth2-proxy-basic-middleware.yaml
  - oauth2-proxy-basic-pdb.yaml