---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-basic
  namespace: auth
spec:
  selector:
    app: oauth2-proxy-basic
  ports:
    - name: http
      port: 4180
      targetPort: 4180
