apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-htpasswd
    namespace: auth
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:5Qbj2Nr7lGWiI1UHXfO3NcJSDIlQ0XoCkiu4iSgg/6z/jYZ2DWih9vMJv4wlA7sBYQsGSbSLBV9Y3Cu95P1uyrJyCLAy/d+ZBI/M,iv:sZ7W487gDOruBCInll7mhx8OEYsHgggvr8em6VfL5d0=,tag:O0DEn7UUm2rBkAOMBgquWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRFpaRDllWUxSaFAzc3Fy
            TFA5TFE2TUp2UGVBQWxVbjkvUGR4WkNiQkhjClRsWVV2NWRzeEEzMHBPRlp4ZWMy
            ODdXQzRFbkRSWHVsbEJEb29yOERXM00KLS0tIEVpcjEydU9OOFZ3bFgxNUx3UEMv
            cHpjYlYyMDhKQkdMU2FIV1FmU3F1czQKz3tDsUqA0ph2VUCek0WRp9nGEAQNxWat
            Nn4AhQrFK4qkdlZ1RmRI2BN878/7Au6e55GaWP4w1X+fixYj8R8N3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T22:32:09Z"
    mac: ENC[AES256_GCM,data:nuVTSbibi+Uv3A1zHFrWwdskOmX/cNWoLsjAE2axGb+U0EV6gvWTTrZIgaUxDQs41YOi4wUK2avx4jtUHdYuhLUxRo4JDoVsUm5CZ/+XE4zsr3d/GQks5fV2HTkRMxV9F+wvuKy2YGRq5Tfgvxo8KtEtBz9olyGOTMKB7AttjaE=,iv:z9efNoTJVVOM5VpL/y1pApFHLryYDs/bwfbUtiDeqgM=,tag:Fz2gpn28vO9fgC3fNXr/Vw==,type:str]
    version: 3.13.3
