apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: auth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:lkadlATdlZuSfNnonf9H0jCOptYc6hHzH1vmscVfEo4=,iv:rJ4+UuIecugcUokeThBi/Q9Ro4TpOV3bHL4xGF+keSc=,tag:xUPcs6SSIaJsnmXcgyjQmg==,type:str]
    client-secret: ENC[AES256_GCM,data:6KrpI7etifVNo4M+saAlVkMvQCn787TmznbT9kUlUIEADEtw9t4rrOYSqo82bVfBSVbqZapHs/Y7AFeXhffiLw==,iv:igQ/NXCs6KrhSQmnr7cbcli0qrmFbuaHq59P4NoShxs=,tag:dM0hNEc+BMTxlkH8HRkagQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:SGx7FxnYE9bmSB9mgGve7de1uUdro0uZla7OQanNFAc=,iv:sZazdg5hfGK5ok5rVaptJXojJnfhPCdGB6dcWuVK67Q=,tag:jlcxuP67pb+zWxHllKqi/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM0x6a0lGRXpYaVRRYm1T
            OWhVR1pSOFBGWWp0UERaNWNVTXhYUWxxK0JjCllzZVAzdGViMld6QkFEUHd3YW44
            TkN5V1cwbjg3d2tjSEZyOGZEdXN4WGMKLS0tIGdxNVZBanlzZVRsUUFqSjNvakI3
            Q0ZrenFkY2tGcTF2TS9sOGRoZ2wrcjAKVW1yUTRGqMC4k0oiklRxFRZA4+iVsZba
            n9Es3aQtZZwWsNgq9mqfEnrxFwlFdGSrd/aUq6rx8WxDmN4UG4MCQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T18:37:03Z"
    mac: ENC[AES256_GCM,data:ka68ibVD/b9ytR1prakwIPTX88NiUj9bMpm8zRvEPbJb42pEd2zJsLbjvWTo0sN/V5SOIPnfsTSjU7BYcLXWNNgF9guNionVZuQQIQlygI92qlDCfl1VNmkS4XbXvvmPKFJEdz2p6sMrXNVH6QV/Qzm1MyITlsbZDPC63ukkGWk=,iv:uIDOrAbGA8ognAlPBg9OuHkQJ/iXjl3RhEqZWa0RBRM=,tag:r9HUNPMGqAbPScGn08K8pw==,type:str]
    version: 3.13.3
