---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  parentRef:
    name: ingress
    namespace: gateway
  listeners:
    - name: oauth
      protocol: HTTPS
      port: 443
      hostname: oauth.i.recompiled.org
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: oauth-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth2-proxy
  namespace: auth
  annotations:
    external-dns.alpha.kubernetes.io/expose: "true"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: oauth2-proxy
      sectionName: oauth
  hostnames:
    - oauth.i.recompiled.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: oauth2-proxy
          port: 4180
