---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth-tls
  namespace: auth
spec:
  secretName: oauth-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - oauth.i.recompiled.org
