apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s-node1
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: lan0
selector:
  match: link.driver == "igc"
---
apiVersion: v1alpha1
kind: LinkConfig
name: lan0
addresses:
  - address: 192.168.1.221/24
routes:
  - gateway: 192.168.1.1
---
apiVersion: v1alpha1
kind: DHCPv6Config
name: lan0
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.1.235
link: lan0
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: drbd
parameters:
  - usermode_helper=disabled
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: drbd_transport_tcp
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: tls
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: dm-thin-pool
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/nvme0n1"
  wipe: false
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 50GiB
  grow: false
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: linstor-pool
provisioning:
  diskSelector:
    match: system_disk
  minSize: 10GiB
  grow: true
