machine:
  network:
    hostname: k8s-node2
    interfaces:
      - deviceSelector:
          driver: r8152
        addresses:
        - 192.168.1.222/24
        dhcp: false
        dhcpOptions:
          ipv6: true
        vip:
          ip: 192.168.1.235
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      - name: dm-thin-pool
  install:
    disk: /dev/nvme0n1
    wipe: false
cluster:
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 50GiB
  grow: false
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: linstor-pool
provisioning:
  diskSelector:
    match: system_disk
  minSize: 10GiB
  grow: true
