apiVersion: v1
kind: Secret
metadata:
    name: volsync-s3-credentials
    namespace: flux-system
type: Opaque
stringData:
    VOLSYNC_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:kgY3hSHEdY8/O/FY1WPQApGO9ns=,iv:0FHaFWVM8vqtF5BxA1KTNmDLjbEzk6ZE/pUxwRyH9yE=,tag:X8cApjy1bM0jsJ4Wk4K4pQ==,type:str]
    VOLSYNC_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E37D47Kwp1oEHNFgJ29K4nqqzcrceiqOWgoQlSnOU/VvGhZWkJm5BFHn,iv:fLwcVEoncaYM78a/i/rTTBWHAiNJQ7xumtsMDuT8eEU=,tag:Wf98zJ0yiknovEGHPIAa6Q==,type:str]
    VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:mUzCW2KtFKqIgesL,iv:4HcBLOmMYSkt1SLBuqMpFa5loYhQtQM+5OW4J2dSo2k=,tag:s5Tc9SnNLn0q4fSGCOqWhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ2xnSnFBL3dQUmFVUUdr
            UXhGZG5kMEdnb05VM0M5eU92S2hDd3Zzc2lBCm1rMEhLcHNlQzZrYnAvTllGeS9R
            NFdBeHU5UGpOYy9ndkNSemszYnp4NWMKLS0tIFg4ZzhiWk1uek80YjNoaGFBZ21G
            d3JIMFI1akZRWmVIblVtK0J3akNHZzAK+dCcNWF/IP2CbRO5/M/Q4gdyQXK7eJbv
            slIG4VcnWsQKbirIuq6t43iHCC7EUI2AI+lh+YQAcBP/EJbG7YEE8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T18:05:55Z"
    mac: ENC[AES256_GCM,data:nBjwredaaJlwd4I7Cj+v/GOBwHSiF3GoteshhHFrpi89K4SgVFweAy0fNYXXvHdnvFEVmJXluaRIO4KZI2JtftwIRFEnkgwNJeCibL6046lNLLvsm4X3fM6Mx+N4xv+C2ihVkaAYVjN3yG5d7swOUME2w9AStxuwiGYG+QGC+Zk=,iv:svaQTuPZ3pS+BrrA+bvNd4DGp4KNEUDzbAFdHE7bN84=,tag:r8b7iqe0XKCNfYH22XhRLw==,type:str]
    version: 3.13.1
