apiVersion: v1
kind: Secret
metadata:
    name: home-cluster-kopia
    namespace: kopiur-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SewdSc1vL38FWuUFCImxEqSVOLQ=,iv:vz+K5YbGy1EK0gg4xEbv3DH3AJs8l7ihxfXEqtOCli8=,tag:xWZ7GML5w+AQF1CI97Ya7Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eb0lKe9ugxvp4NkNvE2SsbTTsZanAMfr+6R/akygDOrjjZfD7a+WLrnP,iv:Q+Crc5WZBiC0axxhjyv3tfwGVA9m/u3OEzOugOPCf7c=,tag:FpezQQj67MCZSdROq2aDJw==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:8awY7thnPsqXtoHGLUKI0BQlqjWuI2j5fTjfR8KH8ZdQLB0DO+/ImJiOk1FG2OQc7/R/Wb6bFCLx6FC5yKO9kQ==,iv:YKly1ZUHB2CDH4NiZbWq8Sw8MHCrbjB+FX7F2vyZSKg=,tag:hYbHBpHWS8UkzVmKLXALog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYkF6ZVpYUTBrVXozSFpX
            dFZ2NE13dmQrck00aXFsVldjWTk5Nm9oQkhBClk0bDdJNDZORmFaK3JKUzU0YnRG
            V2NCQVZPS0VJOVdvOTZtY3NQMlY0TkEKLS0tIHVmY2lINEdLMmVQZG5oWVNoaWo5
            ZmZ4bzYxQldNS0FXUE05RjJEQnRucU0KWyCpI28RblEyTPPknbSbg7HNOso2zMgn
            oeRF0CUo+frNyraoBo0hQIBbGfITWKyMc5/nW58xlCrVUeYj5wm1Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T20:51:51Z"
    mac: ENC[AES256_GCM,data:eCDjcgL0vExpw37eHs2dwTs5Uw1ttb4ymlB15PZM0GEfwU7byagvCgyYGrw6fIXjE9S0aDW+XXMSlnVQ9I5mHtqRHMvKBnh7SRyQ4jIPELdJSqKxvMRNel0ip/H046ZYBHBHsbS58br+Lnr2BE6cMPdU91tN9yfheDfw7mdLeP0=,iv:WhA5CznBM2IAPsm7FhZ8wAEYk4FdXJJbiev+6YdtvOE=,tag:X+pcvVHE82uO0D1K/x0OqQ==,type:str]
    version: 3.13.3
