apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
    annotations:
        recompiled.org/expiry-date: "2026-11-30"
        recompiled.org/expiry-note: CloudFlare API Key Expires November 30, 2026
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:kcgEFWmlLRMUA7pIQVheFy6b1V2tDfVkFgPPTWS4aSEpPdeV49QaOS86/nJWk9tVk7qcTpE=,iv:QTegXMRcKvl8hkoteO/YoviQEHudzbdkKuFr6Xb4BJ8=,tag:iMStwYmLZuNCY+pW1Et8QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcUZyWUFnanJESTR5UGtu
            VXJIY3FFOUpCbnpFcHhVMzJTa2tNMTJ0NndNCisyUDVHSWhFU1M0eUg0QWJkSkhB
            enB4dnhKbjJyc1JSR2JEUVBpbEJsZVkKLS0tIDYwZm56eko4clBlU090Y0x0c3RX
            WldXa09KdEdvNVZBcHJtNHpVdHBSUFkKeYu/lNBuFAflI12jOazeIOQ4aXFjQexb
            z37KJtiKD8g4aB1v4LzN9Ct4k4K25GNLU2KJsngHO+C7FR7dKMV9tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T17:22:22Z"
    mac: ENC[AES256_GCM,data:tnNTOEPjseKQ+C+K6GhXBSLHY+w93cK/xd3XapR4qg1OjIqS+D3Ng2wpX8Og62nd9eRmmfpdbw/e8Qf/r/I/LVkssjZ3OjGwZwgjZCD81FeAbZYQcEf5ejSum+TbvApS/ImSJQkSQ7kdaA76EDWcqBXl9J0dPHj3zHGj7fzC5+M=,iv:pnQIs90AK0QLG5W2qMICGcL62bdNnl44rp/dyZU7P3w=,tag:1PkPpAS+yC8HR9TtMWVvtA==,type:str]
    version: 3.13.1
