{
 "title": "VictoriaMetrics - vmagent (compact)",
 "description": "Overview for VictoriaMetrics vmagent v1.117.0 or higher",
 "tags": [
  "VictoriaMetrics",
  "vmagent"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{job=\"vmagent-global-vmagent\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"vmagent-global-vmagent\"})",
     "legendFormat": "Active targets"
    }
   ]
  },
  {
   "title": "Samples Scraped Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vm_promscrape_samples_scraped_total{job=\"vmagent-global-vmagent\"}[5m])",
     "legendFormat": "{{instance}} samples/sec"
    }
   ]
  },
  {
   "title": "Remote Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vmagent_remotewrite_samples_sent_total{job=\"vmagent-global-vmagent\"}[5m])",
     "legendFormat": "{{instance}} sent/sec"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"vmagent-global-vmagent\"}",
     "legendFormat": "{{instance}} memory"
    }
   ]
  }
 ]
}