apiVersion: v1
kind: Secret
metadata:
    name: sonarr-volsync-restic
    namespace: media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:+yn4/OilfEtwew3JE005p5ZBoh+7xFZTS9ShMgNxGJsv/HHhPVVjBSXvcLp6DW0N82BIp0vbe8Y1B/o+,iv:DXuoqjslkL4yNiGIbmownd38fvKqDyvd8EqnvUT3dIg=,tag:MDcD71JThqQUT1ZHTJwQKw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:O0uT1DRwNWY0T1fu3zzIPoF3WJUg5eLv/aYg3WQc8QRFKxHp6AflqUx/DRk=,iv:AWUyjEiyhp6y+91y2kasx0mbHsfI6+K6+7YqcuWfIPU=,tag:hUDUMSW9NZ1eWWIUwMRVdw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Bs6F4UUov1+fGeeAmEwqqMLak+U=,iv:wq325I7CHOl3Y9+H8dVXLpAA/SpnqVN9BKM8aWU+8gE=,tag:PkYyoiOuvGkbKCAvuXbRig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8J6VAsMcProYEhgpQibCL0jvn7jlkQW0Ild/0qCZxjei5xUm75eomqPU,iv:283iiDJqDWo3pJCZJ8b7NQcxy1VGDWgunzRp9o+/YbM=,tag:jzmbrxRsIH6a9vVyK6VoVA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:XddaV3s/Bfb7,iv:Yf9L8W1PdSBUc51jlaeDtqy4151BaUw+kqBzK8AvlbM=,tag:Zu/zPHtbmglAGjlf43LRnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b2xpb1RCRVJyajZxM0Ir
            TXlPWFd0enIrVkY3c09QM29kanY4cGp1elRJCkJ2SlI5SWU1UC85cS9OQ0FXMi9V
            QXhzc21yU2Z2ZWdxbUpNSjQ1a3E1bEEKLS0tIHRkeHVXSFQ2bnpTZCtyZEJFSWhC
            THI3Q25kbzRvbEpVblNJMThSdjhNL1EK8bE687GntoIgHb0CSBpTaASaugBtt674
            XfyygBGADSHZIgEZ/6x4Kx2s7+qDZIMTvIl9SkrFqR3GYtN1EQCE0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T04:04:13Z"
    mac: ENC[AES256_GCM,data:dqYzMerl2mCXhkH9AToaG50TbPMSd5SLFj2HQsE8aCqUvcznTtHqdDAaeWqwrZVefS+L/UjX7ghZsqHW2KXrcsOGaO4XL5kcoQuAUHpeT0qrkO/UmfqbPZgXtgNX7wL6EwByfepV/4ELxeUIZ5oOm+3i4mc/D5Fx0gha1dGiR1w=,iv:NdevgYa0JxEXQED22m6crtrxY0gKNiDRmFAe6MSSSPg=,tag:sEbsqQWU8V/UgrXmSEf/mw==,type:str]
    version: 3.13.2
