apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  description: PostgreSQL cluster for Forgejo
  instances: 2
  storage:
    size: 2Gi
    storageClass: linstor-r3
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-password
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-forgejo-store
