apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: forgejo
  namespace: forgejo
spec:
  cluster:
    name: forgejo-postgres
  name: forgejo
  login: true
  passwordSecret:
    name: forgejo-db-password
  databaseRoleReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo
  namespace: forgejo
spec:
  cluster:
    name: forgejo-postgres
  name: forgejo
  owner: forgejo
  databaseReclaimPolicy: retain
