apiVersion: v1
kind: Secret
metadata:
    name: cnpg-forgejo-barman-creds
    namespace: forgejo
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:03ZhgQMY6g9UZfWBUZRYMPwmINU=,iv:Y4KLw0VdgErU4lATusLiKca4vwfNpM1et/NEz+BmZJc=,tag:0w255uc/nNVMUbt7LPoSrA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NOY2J2c21FwU073eZH3ECCUgUTGarLBHK/L8+cBYYvjfexrKhbJ2QjYl,iv:lZLD8TITtYf8Juwvfq+rboqcrQ/BVsFTD/9jOVCafKU=,tag:9B7d4XMVolmvlVoHah/PIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aEJaMUJ4MWU4RVdUWUJJ
            YWltZCtZWlh6UlErR0R1UEhzaTliY2ZGU2xrCkwvODRaU1RYTkdwTHlySzNIaERX
            aFhCK2RCL01ZUHZvQUFoUFBnNjE3Z0EKLS0tIHJmWXRrUjRRQ2Vyd0gyNFNaYkdm
            SndNK0pmRjhNbE1Za1FpUWZNUHcyK00KylnF71/gnrOgPKjAsTmYsx0b6MyUWlo2
            vkBKL/0phS/DgkLBIZ1Hf/In0VXdpBHaMmVbbv4llIaEXxK4bt+zYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T17:35:28Z"
    mac: ENC[AES256_GCM,data:AZTL/YwUHFlszfiBzuEi0/qq42wNyUO7xpEb+qjr/Mfis1LCD2egskyiwWSNM+aq/Y04L9plb62GsAqaxfxp9CTKi9YrNrKA++gGg42W+64tvqJo7UGbUljW4HOggZkrYX72xgHO3Og3AoKtfuboz+7pReFeJ2BvvvRF9VUg9IM=,iv:mnyvFl8X6Qh5JK6tKuYDcieZBhLKoykzlLoJiPYngbE=,tag:tg1kdw4DbANc7LeEd+QmBw==,type:str]
    version: 3.13.3
