apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:16.0.5-rootless
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: forgejo-postgres-rw:5432
            - name: FORGEJO__database__SSL_MODE
              value: verify-full
            - name: PGSSLROOTCERT
              value: /etc/postgresql/tls/ca.crt
            - name: FORGEJO__database__NAME
              value: forgejo
            - name: FORGEJO__database__USER
              value: forgejo
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-password
                  key: password
            - name: FORGEJO__server__DOMAIN
              value: forgejo.i.recompiled.org
            - name: FORGEJO__server__ROOT_URL
              value: https://forgejo.i.recompiled.org/
            - name: FORGEJO__server__DISABLE_SSH
              value: "true"
            - name: FORGEJO__service__DISABLE_REGISTRATION
              value: "true"

          volumeMounts:
            - name: forgejo-data
              mountPath: /var/lib/gitea
            - name: postgres-ca
              mountPath: /etc/postgresql/tls
              readOnly: true

          startupProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            periodSeconds: 20
            failureThreshold: 3

      volumes:
        - name: forgejo-data
          persistentVolumeClaim:
            claimName: forgejo-data
        - name: postgres-ca
          secret:
            secretName: forgejo-postgres-ca
            items:
              - key: ca.crt
                path: ca.crt
