apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-secrets.yaml
  - secrets.yaml
  - cnpg-barman-objectstore.yaml
  - cnpg-cluster.yaml
  - cnpg-database.yaml
  - storage.yaml
  - service.yaml
  - httproute.yaml
  - tls-cert.yaml
  - deployment.yaml
