apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-password
    namespace: forgejo
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:d1jFIYPPVg==,iv:poIqjxCNzBEDgP/v9rC37W1UkYhTImoE0PTgtDL/B7M=,tag:cGtiNSn3lMPvrTvlJC8t8Q==,type:str]
    password: ENC[AES256_GCM,data:/1zi+ej3+9HyZA==,iv:4R8+RP4IWwToAKPN0W7j7RSP2oVccfPm6NXGXpQUEG8=,tag:KVRCa6GCKznYCmPL0dYNkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTU9tbDdEWDBENHk0R0dP
            dEEvamQrcnNZaTRyWjZ1T1hGR2hlZXNKNmowCk1vQWtyM2krc1FkZmxCY0swNENj
            MUgvMnpZeXNiUk9CU0F2b0ROcEhMTGcKLS0tIGxVY3gwQmdKY1Vrc1dLU3FoUWht
            cFhhUklrd0JOQ1l0dWhQeDJUUVoxUHMKuXN2loB33eWrDqk4D+sxF2T2mxzLJGp4
            wyg6zvFF8Ok/GL3M8tf/X0ZIaVSdo+uZDHX0FLBCRTri1Us0doDA1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T18:44:30Z"
    mac: ENC[AES256_GCM,data:1MFVpuTXBTmN2/2NJXMZvCEZx0T3uDTuIj+YxwhPaEpdCNBqR+qp6gIJr9Id97OVdXUKxOcFpkonusrml1QySyMgf+mtxhhloacKMYj8HfHYOXvBHv0yQbbm5uJ+J2XJzf254EiyU4ryx73Xnx7FTaSKTG1xGPJeNi2pryzeJrs=,iv:YtNXZeqX9gyqTsRIZXZ/X/2kCsU4TorhD0nSRZpkJRU=,tag:qEwD8GqwuI8fY5g6+7NfHQ==,type:str]
    version: 3.13.3
