apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        recompiled.org/expiry-date: "2026-11-30"
        recompiled.org/expiry-note: CloudFlare API Key Expires November 30, 2026
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:xRAurrb4QjIIejNZyHBOxLzt+veDYZWNQNOgK3zu1c479SBm6v26OOVmdMw2VkUN6kYLQQU=,iv:w637ClMCAVfm1Lo8NDGRsbm+I86ArS31hFm/JyW7vHY=,tag:dezft1Quh2RvGWvlfW82IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbWxrV09qVjVpS2hxcVJo
            b2tvUjIxTGZsMGN1L0I5Y1NaNy9jMVhBQzJjCmN2NnVhZ1hqdVA1REF2RXZsNXBq
            cURqV1hqU3VETGFJUzByckcyRisza1EKLS0tIEM2eFAzWjdIc21RNUVESGlUY1lx
            QWROZEdsWmFIUDliNnREek5OTkF0WE0KYRFAGlyABXVcknQHAOBQMvmoxFSOq/IA
            h1ZiaM/cKGRp6xVzy8s5l6uCLeRDsvdQqX4VXZGhYNcxS5P1fpKn9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T17:24:04Z"
    mac: ENC[AES256_GCM,data:qSsmR2i8NB1rpjRsHeV9onhSVIoVm4t90qOJz/Fi6idKm6SRuIGBqM/Ewc/jrmnAYFh0Bjr5s/hba0P+oRvem6G9UkptEDGY1OjZBgWGbaxE4OmgtjuvJLry3SWoli5l70lhQXbRHMkzl+nxAClvKXvSn5jrH1tlFLToCfSrIWc=,iv:IKHkvT8nRT9CEWO2q58gw/A0VSYuFHAOGVzE5tbbnBQ=,tag:Ug1ghOHQOkx+yY7C8S8ymw==,type:str]
    version: 3.13.1
