apiVersion: v1
kind: Secret
metadata:
    name: volsync-restic-credentials
    namespace: flux-system
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:XCN28E5BJkMGnp1D,iv:GcQIgnKuyNaaleNeyNOhPQWePEggwoq4Gdv+OQHkjYo=,tag:RKSdvOOTu4wk3tXz/cGG0Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MEAswtpK1NVfwqb9vb2RtOoX5Uk=,iv:OSPZJGSFaPTNVsKXBzzB9uARgjEKBvYTOz1e+4i5czc=,tag:IbpEcKZttnE5/Sq1YtTrDg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GXpjh7ayurXc9tfba0nNoZiaYH/km2/4+2Hld6bHggbntXe0+7Z9fP3a,iv:LKfJXh24lCQy4ypI9xS+8g81s8lcVSLQkG/43X7Ix+c=,tag:pF8/x9gYovTOozcpTvR7lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNDF2SWRibXpQRWJDbE94
            UndaMGY2bEs0elhYZFhMVml4SWEwR1FLQUQ0CjZzWXMvTjVzZzljeHBPRXdOcU5C
            MVBlVktUampTS1NZc2kwbVRaK2szeEUKLS0tIFowS3NaQno4K0tnQzQ4SUVxSHdR
            a3dQSHBmVHdmRWdjWnQrK0hwczlUencK0ehxLo5Z0jVIYISs3XspvPWrtK5LC+8A
            hTBhRiyi+muHdFf1Q9DeRz+277PLGlcthr3gKOCiSRzBbtqq464myA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smj04f0u6867c0yhlsjly6c5qcty8gdsnzhahpx2z8fr6sxdws3qgd9aut
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T03:52:32Z"
    mac: ENC[AES256_GCM,data:PDVBksKvpMdNfo26U8E/Zn7y6lcyTr+LTbBCQjvfmB0e2xEShrpt3j3dGEu56oiHpgERv3o4rKWsh7Hg4SGU6LHUpSLw++uxIDiQQ8VIi60iDl52IO/2UhvL0NpAwc6Lxzmumpb/ZlANdMT/AczuJlVgC0ebEUu7ESfESxFd1s0=,iv:8HjsNDNWzMnmbkKC8vCPQiNuMvOCRpVrTaXcukwFA6I=,tag:tne4hjxb9ysoMe6X9uMmpA==,type:str]
    version: 3.13.1
