---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: overseerr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/expose: "true"
spec:
  parentRef:
    name: ingress
    namespace: gateway
  listeners:
    - name: overseerr
      protocol: HTTPS
      port: 443
      hostname: overseerr.i.recompiled.org
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: overseerr-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: overseerr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/expose: "true"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: overseerr
      sectionName: overseerr
  hostnames:
    - overseerr.i.recompiled.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: overseerr
          port: 5055
