apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bindery-snapshotpolicy.yaml
  - bindery-snapshotschedule.yaml
  - plex-snapshotpolicy.yaml
  - plex-snapshotschedule.yaml
  - tautulli-snapshotpolicy.yaml
  - tautulli-snapshotschedule.yaml
