apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volume-snapshot-class.yaml
  # Proving the chain with overseerr first; remaining 11 added after verification.
  - repositories/overseerr.yaml
  - replicationsources/overseerr.yaml
